receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

processors:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors: []
      exporters:
      - logging
